### ISSUE TITLE
cls error

### ISSUE THREAD

**Issue by geshifuyun333** [Xequinox16/SoundCloud-Downloader#1]
no use

**Comment by Xequinox16** [comment]
What bro

**Comment by geshifuyun333** [comment]
-bash-3.2$ python3 /Users/xuke/Desktop/SoundCloud-Downloader-master/main.py 
sh: -c: line 0: unexpected EOF while looking for matching `''
sh: -c: line 1: syntax error: unexpected end of file
sh: cls: command not found
Xequinox's Soundcloud Downloader
###################################
[1] - Download Playlist From Url
[2] - Download Track From Url
###################################
#>1
sh: cls: command not found
Enter A Playlist Url: https://soundcloud.com/user-317540672/sets/piano-3
sh: cls: command not found
Do You Want To Use ID3 Tags? [Y/N]: y
sh: cls: command not found

can u fix this or tell me how to run it

**Comment by Xequinox16** [comment]
What OS did you run it with, use windows

**Comment by Xequinox16** [comment]
Try now

**Comment by geshifuyun333** [comment]
mac bro.do u have a chat account.esaier to communicate

**Comment by Xequinox16** [comment]
Steam: https://steamcommunity.com/id/Xequinox16
Discord: Xequinox#2627
